name: CI

on:
  push:
    branches: [ main, develop-2 ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests and collect coverage
      run: |
        pytest

    - name: Run flake8 static analysis
      run: |
        flake8 .

    - name: Run memory profiling
      run: |
        mprof run python src/bookstore.py
        mprof plot